package com.dubbo.demo.springbootdubboapi.enetity;

import lombok.Data;

@Data
public class Store {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.id
     *
     * @mbggenerated Thu Jan 03 16:31:51 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.store_name
     *
     * @mbggenerated Thu Jan 03 16:31:51 CST 2019
     */
    private String storeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.del_flag
     *
     * @mbggenerated Thu Jan 03 16:31:51 CST 2019
     */
    private String delFlag;

}
